title: 0h-n0 Blog
description: Machine Learning & Rust & Drug Discovery
show_downloads: true

baseurl: "/blog" # change this to the subpath of your site, e.g. /blog. Leave it empty if you don't need it.
url: "https://0h-n0.github.io" # change this to the base hostname & protocol for your site


google_analytics: "UA-164327210-1"


# cayman-blog date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
cayman-blog:
  date_format: "%b %-d, %Y"

theme: # leave it empty

# social
author: 0h-n0
image: /thumbnail-jumbo.png
twitter:
  username: 0h-n0

plugins:
  - jekyll-target-blank

target-blank:
    rel: nofollow

header_page_refs: ['now', 'about', 'contact']
